services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - NODE_ENV=dev
      - PORT=3000
      - DEV_DB_URI=postgres://rujlehga:FVCuYbRM6Rp7aqpKP10qpeV4UW6onjJU@mouse.db.elephantsql.com/rujlehga
      - DB_PORT=5432
      - DB_USER=rujlehga
      - RECAPTCHA_SECRET=s3I6#BK5
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 3000:3000
    depends_on:
      - postgres
    links:
      - postgres:postgres
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev

  postgres:
    image: postgres:alpine
    restart: always
    environment:
      - DEV_DB_URI=postgres://rujlehga:FVCuYbRM6Rp7aqpKP10qpeV4UW6onjJU@mouse.db.elephantsql.com/rujlehga
      - DB_USER=rujlehga
      - POSTGRES_HOST_AUTH_METHOD=trust
